### ISSUE TITLE
Not working with svelte-kit

### ISSUE THREAD

**Issue by tw1t611** [leafOfTree/svelte-lazy#13]
Using it with svelte-kit, I get the following error:

```bash
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at Placeholder.svelte:5:45
    at Object.$$render (/home/user/Projects/ari-motors-v2/node_modules/svelte/internal/index.js:1555:22)
    at eval (/node_modules/svelte-lazy/src/index.svelte:179:94)
    at Object.$$render (/home/user/Projects/ari-motors-v2/node_modules/svelte/internal/index.js:1555:22)
    at Image.svelte:48:14
    at Object.$$render (/home/user/Projects/ari-motors-v2/node_modules/svelte/internal/index.js:1555:22)
    at eval (/src/lib/core/BackgroundImage.svelte:15:84)
    at Object.$$render (/home/user/Projects/ari-motors-v2/node_modules/svelte/internal/index.js:1555:22)
    at PlatformSelection.svelte:19:28
```

Implementation: (Installed with `yarn add -D svelte-lazy`)

```js
import Lazy from "svelte-lazy";

<Lazy height={100}>
  <img src="/images/logo.png" alt="logo" />
</Lazy>
```

Does return the same error with and without a placeholder.

**Comment by leafOfTree** [comment]
Thanks, @tw1t611. The fix is to check if the placeholder is empty. I've deployed it to https://www.npmjs.com/package/svelte-lazy/v/1.0.10. Please upgrade it and see if it works for you.

**Comment by tw1t611** [comment]
@leafOfTree wow, you are great. Just works. Thank you. :)
